version: '3.8'

services:
  game:
    container_name: game
    build:
      context: "./backend/Game"
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - game_db
    env_file:
      - .env
    networks:
      - microservices-network

  redis:
    image: "redis:alpine"
    container_name: redis
    networks:
      - microservices-network
    expose:
      - 6379

  usermanagement:
    container_name: usermanagement
    build:
      context: "./backend/usermanagement"
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    depends_on:
      - usermanagement_db
    env_file:
      - .env
    networks:
      - microservices-network
    volumes:
      - usermanagement_media_data:/app/media

  # frontend:
    # container_name: frontend
    # build: 
    #   context: "./frontend"
    #   dockerfile: Dockerfile
    # ports:
    #   - "5173:5173"
    # env_file:
    #   - .env
    # volumes:
    #   - front_vm:/app
    #   - /app/node_modules
    # networks:
    #   - microservices-network
    
  notifications:
    container_name: notifications
    build:
      context: "./backend/notifications"
      dockerfile: Dockerfile
    ports:
      - 8002:8000
    depends_on:
      - notif_db
      - redis
    env_file:
      - .env
    networks:
      - microservices-network

  chat:
    container_name: chat
    build:
      context: "./backend/ChatService"
      dockerfile: Dockerfile
    ports:
      - 8003:8000
    depends_on:
      - chat_db
      - redis
    env_file:
      - .env
    networks:
      - microservices-network

  nginx:
    image: nginx:alpine
    container_name: mynginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - usermanagement_media_data:/usr/share/nginx/media
    ports:
      - "80:80"
    depends_on:
      - game
      - usermanagement
      - notifications
      - chat
    networks:
      - microservices-network

  usermanagement_db:
    image: postgres:15-alpine
    container_name: usermanagement_db
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - usermanagement_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  game_db:
    image: postgres:15-alpine
    container_name: game_db
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - game_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  notif_db:
    image: postgres:15-alpine
    container_name: notif_db
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - notif_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network
  
  chat_db:
    image: postgres:15-alpine
    container_name: chat_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - chat_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

volumes:
  game_db_data:
  notif_db_data:
  usermanagement_db_data:
  chat_db_data:
  usermanagement_media_data:
  front_vm:

networks:
  microservices-network:
    driver: bridge
