version: '3.8'

services:
  game:
    container_name: game
    build:
      context: "./backend/Game"
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    env_file:
      - .env
    networks:
      - game-network

  redis:
    image: "redis:alpine"
    container_name: redis
    networks:
      - game-network
    expose:
      - 6379

  usermanagement:
    container_name: usermanagement
    build:
      context: "./backend/usermanagement"
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    env_file:
      - .env

  # frontend:
  #     container_name: frontend
  #     build: 
  #       context: "./frontend"
  #       dockerfile: Dockerfile
  #     ports:
  #       - "5173:5173"
  #     env_file:
  #       - .env
  
  db:
    image: postgres:15-alpine
    container_name: db
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - game-network


volumes:
  db_data:

networks:
  game-network:
    driver: bridge